---
# file: roles/haproxy/tasks/main.yml
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - haproxy
    - haproxy-install
    - haproxy-firewall
    - haproxy-selinux
    - haproxy-config
    - haproxy-sysctl

- name: config | Setting Facts
  set_fact:
    haproxy_bindnet_addr: "{{ hostvars[inventory_hostname]['ansible_' + haproxy_bindnet_interface]['ipv4']['address'] }}"

- include: install.yml
  tags: [ haproxy, haproxy-install ]

- include: firewall.yml
  tags: [ haproxy, haproxy-firewall ]
  when: haproxy_firewalld is defined and
        haproxy_firewalld | bool

- include: selinux.yml
  tags: [ haproxy, haproxy-selinux ]
  when: haproxy_selinux | bool

- include: config.yml
  tags: [ haproxy, haproxy-config ]

- include: sysctl.yml
  tags: [ haproxy, haproxy-sysctl ]

- include: pacemaker.yml
  when: haproxy_pacemaker_support is defined and
        haproxy_pacemaker_support == true
  tags: [ haproxy, haproxy-pacemaker ]
